# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSApp
  pod 'SDWebImage', '~> 5.0'
  pod 'KeychainAccess', '~> 4.1.0'
  pod 'Moya', '~> 14.0.0'
  
  # JSON
  pod 'ObjectMapper', '~> 3.5.1'
  pod 'SwiftyJSON', '~> 5.0.0'

  target 'iOSAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSAppUITests' do
    # Pods for testing
  end

end
